
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int LSQPAR = 25;
  public static final int ELSE = 10;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int INT = 12;
  public static final int DIGIT = 29;
  public static final int SEMI = 2;
  public static final int WHILE = 15;
  public static final int DEVIDED_BY = 16;
  public static final int RETURN = 13;
  public static final int NOT_EQUAL = 23;
  public static final int GREATER = 19;
  public static final int IF = 11;
  public static final int LCURLBRACE = 27;
  public static final int LPAREN = 7;
  public static final int ID = 9;
  public static final int NUM = 30;
  public static final int EQUALS = 21;
  public static final int COMMA = 24;
  public static final int EOF = 0;
  public static final int MINUS = 4;
  public static final int LESS_OR_EQUAL = 18;
  public static final int error = 1;
  public static final int RCURLBRACE = 28;
  public static final int GREATER_OR_EQUAL = 20;
  public static final int RSQPAR = 26;
  public static final int ASSIGNMENT = 22;
  public static final int VOID = 14;
  public static final int LESS = 17;
  public static final int UMINUS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "ID",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "DEVIDED_BY",
  "LESS",
  "LESS_OR_EQUAL",
  "GREATER",
  "GREATER_OR_EQUAL",
  "EQUALS",
  "ASSIGNMENT",
  "NOT_EQUAL",
  "COMMA",
  "LSQPAR",
  "RSQPAR",
  "LCURLBRACE",
  "RCURLBRACE",
  "DIGIT",
  "NUM"
  };
}

